export const siswaActionTypes = {
    GET_SISWA_SUCCESS: "GET_SISWA_SUCCESS",
    GET_SISWA_FAILED: "GET_SISWA_FAILED",
    GET_SISWA_REQUEST: "GET_SISWA_REQUEST",

    CREATE_SISWA_REQUEST: "CREATE_SISWA_REQUEST",
    CREATE_SISWA_SUCCESS: "CREATE_SISWA_SUCCESS",
    CREATE_SISWA_FAILED: "CREATE_SISWA_FAILED",

    UPDATE_SISWA_REQUEST: "UPDATE_SISWA_REQUEST",
    UPDATE_SISWA_SUCCESS: "UPDATE_SISWA_SUCCESS",
    UPDATE_SISWA_FAILED: "UPDATE_SISWA_FAILED",
    
    DELETE_SISWA_REQUEST: "DELETE_SISWA_REQUEST",
    DELETE_SISWA_SUCCESS: "DELETE_SISWA_SUCCESS",
    DELETE_SISWA_FAILED: "DELETE_SISWA_FAILED",
};
